using System.Runtime.InteropServices;
using Silk.NET.OpenGL;
using Silk.NET.Windowing;
using StbTrueTypeSharp;

namespace Gorillas.Engine
{
    public class Fonts
    {
        // Font Configuration
        private const string _fontPath = "Px437_IBM_VGA_SquarePx.ttf";
        private const float _fontSize = 16f; // Match the native font size (usually 8, 14, or 16)
        private static StbTrueType.stbtt_fontinfo _fontInfo;
        private static byte[] _fontBuffer;

public unsafe Fonts()
        {
            // Load the TTF file into memory
            _fontBuffer = File.ReadAllBytes(_fontPath);
            _fontInfo = StbTrueType.CreateFont(_fontBuffer, 0);

            // Allocate space in unmanaged memory
            byte* unmanagedBuffer = (byte*)Marshal.AllocHGlobal(_fontBuffer.Length);
            Marshal.Copy(_fontBuffer, 0, (IntPtr)unmanagedBuffer, _fontBuffer.Length);

            bool success = StbTrueType.stbtt_InitFont(_fontInfo, unmanagedBuffer, 0);

            if (_fontInfo == null)
                throw new Exception("Failed to initialize oldschool ttf font.");

            // 3. Create the OpenGL target texture
            textureId = Gl.GenTexture();
            Gl.BindTexture(TextureTarget.Texture2D, textureId);

            // Use NEAREST filtering to keep the low-res pixels perfectly crisp when upscaled
            Gl.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMinFilter, (int)GLEnum.Nearest);
            Gl.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMagFilter, (int)GLEnum.Nearest);

            // Draw dummy initial string onto our CPU array
            RenderTextToBuffer("HELLO WORLD!", 10, 20, 255, 255, 255);
            RenderTextToBuffer("DOS MODE EN-CA READY.", 10, 40, 0, 255, 0);
        }

        private void RenderTextToBuffer(string text, int startX, int startY, byte r, byte g, byte b, byte a = 255)
        {
            // Determine sizing metric scale
            float scale = StbTrueType.stbtt_ScaleForPixelHeight(_fontInfo, _fontSize);

            int ascent, descent, lineGap;
            StbTrueType.stbtt_GetFontVMetrics(_fontInfo, out ascent, out descent, out lineGap);
            int baseline = (int)(ascent * scale);

            int currentX = startX;

            foreach (char c in text)
            {
                // Get sizing and boundary metrics for this character
                int advanceWidth, leftSideBearing;
                StbTrueType.stbtt_GetCodepointHMetrics(_fontInfo, c, out advanceWidth, &leftSideBearing);

                int ix1, iy1, ix2, iy2;
                StbTrueType.stbtt_GetCodepointBitmapBox(_fontInfo, c, scale, scale, &ix1, &iy1, &ix2, &iy2);

                int glyphWidth = ix2 - ix1;
                int glyphHeight = iy2 - iy1;

                if (glyphWidth > 0 && glyphHeight > 0)
                {
                    // Allocate temporary alpha memory for character extraction
                    byte[] monoBitmap = new byte[glyphWidth * glyphHeight];

                    fixed (byte* pBitmap = monoBitmap)
                    {
                        StbTrueType.stbtt_MakeCodepointBitmap(_fontInfo, pBitmap, glyphWidth, glyphHeight, glyphWidth, scale, scale, c);
                    }

                    // Render mono data into the main RGBA array
                    int targetY = startY + baseline + iy1;

                    for (int srcY = 0; srcY < glyphHeight; srcY++)
                    {
                        int pixelY = targetY + srcY;
                        if (pixelY < 0 || pixelY >= BufferHeight) continue;

                        for (int srcX = 0; srcX < glyphWidth; srcX++)
                        {
                            int pixelX = currentX + (int)(leftSideBearing * scale) + srcX;
                            if (pixelX < 0 || pixelX >= BufferWidth) continue;

                            // Extract the alpha value generated by the parser
                            byte alphaSample = monoBitmap[srcY * glyphWidth + srcX];

                            // ALIASING THRESHOLD CRITICAL: Force bitmask values to prevent anti-aliasing blur
                            if (alphaSample > 0)
                            {
                                int bufferIndex = (pixelY * BufferWidth + pixelX) * 4;
                                pixelBuffer[bufferIndex + 0] = r; // R
                                pixelBuffer[bufferIndex + 1] = g; // G
                                pixelBuffer[bufferIndex + 2] = b; // B
                                pixelBuffer[bufferIndex + 3] = 255; // Alpha
                            }
                        }
                    }
                }

                // Push position index forward based on tracking data
                currentX += (int)(advanceWidth * scale);
            }
        }
    }
}
