using System;
using System.IO;
using Silk.NET.OpenGL;
using Silk.NET.Windowing;
using StbTrueTypeSharp;

namespace RetroTextRenderer
{
    class Program
    {
        private static IWindow window;
        private static GL Gl;

        // Low-resolution CPU canvas dimensions
        private const int BufferWidth = 320;
        private const int BufferHeight = 240;
        private static byte[] pixelBuffer;

        // OpenGL Texture Handle
        private static uint textureId;

        // Font Configuration
        private const string FontPath = "Px437_IBM_VGA_SquarePx.ttf";
        private const float FontSize = 16f; // Match the native font size (usually 8, 14, or 16)
        private static StbTrueType.stbtt_fontinfo fontInfo;
        private static byte[] fontBuffer;

        static void Main(string[] args)
        {
            var options = WindowOptions.Default;
            options.Size = new Silk.NET.Maths.Vector2D<int>(640, 480); // Upscaled window size
            options.Title = "Retro Text Buffer";

            window = Window.Create(options);
            window.Load += OnLoad;
            window.Render += OnRender;
            window.Run();
        }

        private static void OnLoad()
        {
            Gl = GL.GetApi(window);

            // 1. Allocate RGBA CPU pixel buffer (initialized to transparent black)
            pixelBuffer = new byte[BufferWidth * BufferHeight * 4];

            // 2. Load the TTF file into memory
            fontBuffer = File.ReadAllBytes(FontPath);
            fontInfo = StbTrueType.stbtt_InitFont(fontBuffer);
            if (fontInfo == null)
                throw new Exception("Failed to initialize oldschool ttf font.");

            // 3. Create the OpenGL target texture
            textureId = Gl.GenTexture();
            Gl.BindTexture(TextureTarget.Texture2D, textureId);

            // Use NEAREST filtering to keep the low-res pixels perfectly crisp when upscaled
            Gl.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMinFilter, (int)GLEnum.Nearest);
            Gl.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMagFilter, (int)GLEnum.Nearest);

            // Draw dummy initial string onto our CPU array
            RenderTextToBuffer("HELLO WORLD!", 10, 20, 255, 255, 255);
            RenderTextToBuffer("DOS MODE EN-CA READY.", 10, 40, 0, 255, 0);
        }

        private static void RenderTextToBuffer(string text, int startX, int startY, byte r, byte g, byte b)
        {
            // Determine sizing metric scale
            float scale = StbTrueType.stbtt_ScaleForPixelHeight(fontInfo, FontSize);

            int ascent, descent, lineGap;
            StbTrueType.stbtt_GetFontVMetrics(fontInfo, out ascent, out descent, out lineGap);
            int baseline = (int)(ascent * scale);

            int currentX = startX;

            foreach (char c in text)
            {
                // Get sizing and boundary metrics for this character
                int advanceWidth, leftSideBearing;
                StbTrueType.stbtt_GetCodepointHMetrics(fontInfo, c, out advanceWidth, &leftSideBearing);

                int ix1, iy1, ix2, iy2;
                StbTrueType.stbtt_GetCodepointBitmapBox(fontInfo, c, scale, scale, &ix1, &iy1, &ix2, &iy2);

                int glyphWidth = ix2 - ix1;
                int glyphHeight = iy2 - iy1;

                if (glyphWidth > 0 && glyphHeight > 0)
                {
                    // Allocate temporary alpha memory for character extraction
                    byte[] monoBitmap = new byte[glyphWidth * glyphHeight];

                    fixed (byte* pBitmap = monoBitmap)
                    {
                        StbTrueType.stbtt_MakeCodepointBitmap(fontInfo, pBitmap, glyphWidth, glyphHeight, glyphWidth, scale, scale, c);
                    }

                    // Render mono data into the main RGBA array
                    int targetY = startY + baseline + iy1;

                    for (int srcY = 0; srcY < glyphHeight; srcY++)
                    {
                        int pixelY = targetY + srcY;
                        if (pixelY < 0 || pixelY >= BufferHeight) continue;

                        for (int srcX = 0; srcX < glyphWidth; srcX++)
                        {
                            int pixelX = currentX + (int)(leftSideBearing * scale) + srcX;
                            if (pixelX < 0 || pixelX >= BufferWidth) continue;

                            // Extract the alpha value generated by the parser
                            byte alphaSample = monoBitmap[srcY * glyphWidth + srcX];

                            // ALIASING THRESHOLD CRITICAL: Force bitmask values to prevent anti-aliasing blur
                            if (alphaSample > 0)
                            {
                                int bufferIndex = (pixelY * BufferWidth + pixelX) * 4;
                                pixelBuffer[bufferIndex + 0] = r; // R
                                pixelBuffer[bufferIndex + 1] = g; // G
                                pixelBuffer[bufferIndex + 2] = b; // B
                                pixelBuffer[bufferIndex + 3] = 255; // Alpha
                            }
                        }
                    }
                }

                // Push position index forward based on tracking data
                currentX += (int)(advanceWidth * scale);
            }
        }

        private static void OnRender(double obj)
        {
            Gl.Clear((uint)GLEnum.ColorBufferBit);

            // Update the OpenGL GPU texture context memory with our raw pixel modifications
            Gl.BindTexture(TextureTarget.Texture2D, textureId);
            fixed (byte* pData = pixelBuffer)
            {
                Gl.TexImage2D(TextureTarget.Texture2D, 0, InternalFormat.Rgba, (uint)BufferWidth, (uint)BufferHeight, 0, PixelFormat.Rgba, PixelType.UnsignedByte, pData);
            }

            // Blit / draw texture onto full window dimensions
            // In modern OpenGL cores, substitute this block with your layout shader mesh program
            Gl.Enable(EnableCap.Texture2D);
            Gl.Begin(PrimitiveType.Quads);
            Gl.TexCoord2(0, 0); Gl.Vertex2(-1, 1);  // Top Left
            Gl.TexCoord2(1, 0); Gl.Vertex2(1, 1);   // Top Right
            Gl.TexCoord2(1, 1); Gl.Vertex2(1, -1);  // Bottom Right
            Gl.TexCoord2(0, 1); Gl.Vertex2(-1, -1); // Bottom Left
            Gl.End();
        }
    }
}
